import type {
  CourseHyperlattice,
  HyperlatticeEdge,
  HyperlatticeNode,
  JarrasCourseModule,
  JarrasFigureSpec,
  JarrasInvariant,
  MovementAtom,
  MovementFormula,
} from './types.js'

export const JARRAS_INVARIANTS: readonly JarrasInvariant[] = Object.freeze([
  'no_transport',
  'no_coercion',
  'safe_replay',
  'trace_preserved',
  'pi_fixed',
  'body_boundary_preserved',
  'authorship_preserved',
  'plurality_not_collapsed',
  'public_internal_separated',
  'consent_first',
])

export const MOVEMENT_ATOMS: readonly MovementAtom[] = Object.freeze([
  {
    id: 'updown',
    label: 'Updown',
    layer: 'pelvis',
    cue: 'Aislamiento vertical de pelvis con centro estable.',
    visual: 'Flecha doble arriba/abajo sobre eje pélvico.',
    safety: ['rango cómodo', 'rodillas suaves', 'pausa disponible'],
  },
  {
    id: 'jiggle',
    label: 'Jiggle',
    layer: 'pelvis',
    cue: 'Vibración rápida por soltura regulada, no por fuerza invasiva.',
    visual: 'Microondas alrededor de pelvis/glúteos como release wave.',
    safety: ['soltar sin colapsar', 'bajar intensidad si hay dolor'],
  },
  {
    id: 'tiktok',
    label: 'Tiktok',
    layer: 'pelvis',
    cue: 'Marcaje lateral tipo reloj con pulso claro.',
    visual: 'Péndulo lateral / dial de reloj pélvico.',
    safety: ['no bloquear respiración', 'mantener salida disponible'],
  },
  {
    id: 'bounce',
    label: 'Bounce',
    layer: 'groove',
    cue: 'Rodillas vivas, peso elástico y rebote grounded.',
    visual: 'Resorte vertical conectado a pies y cadera.',
    safety: ['aterrizar suave', 'cuidar tobillos y rodillas'],
  },
  {
    id: 'wave',
    label: 'Wave',
    layer: 'groove',
    cue: 'Onda continua por columna, brazos y pelvis.',
    visual: 'Curva sinusoidal atravesando cuerpo y espacio.',
    safety: ['no forzar amplitud', 'seguir respiración'],
  },
  {
    id: 'rockin',
    label: 'Rockin',
    layer: 'groove',
    cue: 'Peso delante/detrás con suspensión, actitud y memoria hiphop.',
    visual: 'Eje pendular con transferencia de peso.',
    safety: ['mantener equilibrio', 'cambiar dirección sin prisa'],
  },
  {
    id: 'shake',
    label: 'Shake',
    layer: 'composition',
    cue: 'Aceleración breve como acento dentro de fórmula compuesta.',
    visual: 'Campo de vibración corto anclado al pulso.',
    safety: ['usar como acento', 'no sostener si fatiga'],
  },
  {
    id: 'floor-drop',
    label: 'Floor drop',
    layer: 'floorwork',
    cue: 'Descenso regulado hacia suelo como estado metaestable.',
    visual: 'Curva de energía que baja, toca suelo y retorna.',
    safety: ['suelo como soporte', 'opción de no bajar', 'recuperación lenta'],
  },
  {
    id: 'pause',
    label: 'Pause',
    layer: 'safety',
    cue: 'Parar, mirar u observar cuenta como práctica.',
    visual: 'Nodo de reposo con borde luminoso y salida abierta.',
    safety: ['pausa siempre disponible', 'mirar también participa'],
  },
])

export const MOVEMENT_FORMULAS: readonly MovementFormula[] = Object.freeze([
  {
    id: 'cuadradinho-brega-funk',
    label: 'Cuadradinho Brega Funk',
    atoms: ['tiktok', 'updown'],
    geometry: 'square',
    rhythm: 'síncopa brega funk',
    rule: 'Tiktok abre esquinas; updown marca verticalidad sin perder centro.',
  },
  {
    id: 'hexagonin-jaraniano',
    label: 'Hexagonín Jaraniano',
    atoms: ['tiktok', 'updown', 'shake'],
    geometry: 'hexagon',
    rhythm: 'CLICK42 / jarras pulse',
    rule: 'Seis direcciones, tres átomos, una traza replay-safe.',
  },
  {
    id: 'jarras-choreo-compose-anything',
    label: 'Jarras Choreo Compose Anything',
    atoms: ['wave', 'bounce', 'rockin', 'pause'],
    geometry: 'graph',
    rhythm: 'Synclavier-like transition grid',
    rule: 'Cualquier frase puede conectar si preserva respiración, consentimiento, salida y pulso.',
  },
  {
    id: 'groove-to-metastable-state',
    label: 'Groove to Metastable State',
    atoms: ['bounce', 'rockin', 'floor-drop', 'pause'],
    geometry: 'cycle',
    rhythm: 'old-school floorwork recovery',
    rule: 'Bajar no es fallar: el suelo recibe, estabiliza y permite retorno.',
  },
])

export const COURSE_MODULES: readonly JarrasCourseModule[] = Object.freeze([
  {
    id: 'pelvic-foundation',
    title: 'Pasos básicos de twerk',
    purpose: 'Afina pelvis como instrumento de pulso, centro y regulación.',
    atoms: ['updown', 'jiggle', 'tiktok'],
    formulas: [],
    historicalContext: ['New Orleans bounce', 'club practice', 'body-memory pedagogy'],
    soundContext: ['CLICK24', 'CLICK42'],
    invariants: JARRAS_INVARIANTS,
  },
  {
    id: 'hiphop-groove',
    title: 'Grooves hiphop',
    purpose: 'Integra bounce, wave y rockin como peso, pulso y memoria.',
    atoms: ['bounce', 'wave', 'rockin'],
    formulas: [],
    historicalContext: ['hiphop', 'waacking', 'jazz roots', 'queer club history'],
    soundContext: ['postdisco', 'posthouse', 'posttechno'],
    invariants: JARRAS_INVARIANTS,
  },
  {
    id: 'composition-lab',
    title: 'Composiciones de autor',
    purpose: 'Construye fórmulas JJBV/Jarras Khoreo sin cerrar rutas de improvisación.',
    atoms: ['updown', 'tiktok', 'shake', 'wave', 'bounce', 'rockin'],
    formulas: ['cuadradinho-brega-funk', 'hexagonin-jaraniano', 'jarras-choreo-compose-anything'],
    historicalContext: ['brega funk', 'hiphop choreo lab', 'dance as archive'],
    soundContext: ['Synclavier', 'Frank Zappa', 'Moroder pulse'],
    invariants: JARRAS_INVARIANTS,
  },
  {
    id: 'floor-metastability',
    title: 'Caídas al suelo',
    purpose: 'Trata el descenso como transición a estado metaestable y retorno seguro.',
    atoms: ['floor-drop', 'pause', 'bounce', 'rockin'],
    formulas: ['groove-to-metastable-state'],
    historicalContext: ['old school stripper choreography', 'exotic pole dance references'],
    soundContext: ['slow groove', 'club bass'],
    invariants: JARRAS_INVARIANTS,
  },
  {
    id: 'somatic-sensorial',
    title: 'Baile sensorial somático',
    purpose: 'Entrena sentir, disfrutar y percibir integrando sentidos internos y externos.',
    atoms: ['wave', 'pause', 'jiggle'],
    formulas: [],
    historicalContext: ['somatic dance', 'skin boundary work', 'care as structure'],
    soundContext: ['psychedelic anatolian', 'arabic', 'turkish', 'french postclub'],
    invariants: JARRAS_INVARIANTS,
  },
  {
    id: 'eulerian-improvisation',
    title: 'Camino aleatorio euleriano',
    purpose: 'Usa frases de hiphop como nodos que se visitan y vuelven a centro.',
    atoms: ['updown', 'tiktok', 'bounce', 'wave', 'rockin', 'floor-drop', 'pause', 'shake'],
    formulas: ['jarras-choreo-compose-anything'],
    historicalContext: ['improvisation', 'graphical calculus', 'hyperlattice routes'],
    soundContext: ['CLICK42', 'SonicPi'],
    invariants: JARRAS_INVARIANTS,
  },
  {
    id: 'sound-synthesis',
    title: 'Quantum Instrumentality',
    purpose: 'Mapea cuerpo como sintetizador: pelvis, respiración, columna, pies, manos y mirada.',
    atoms: ['updown', 'jiggle', 'tiktok', 'bounce', 'wave', 'rockin'],
    formulas: ['hexagonin-jaraniano'],
    historicalContext: ['Moog', 'Moroder', 'Daft Punk', 'Synclavier', 'Frank Zappa'],
    soundContext: ['Moog', 'Moroder', 'Daft Punk', 'CLICK24', 'CLICK42', 'Synclavier', 'SonicPi'],
    invariants: JARRAS_INVARIANTS,
  },
  {
    id: 'queer-bounce-lineage',
    title: 'Trasfondo histórico del bounce',
    purpose: 'Honra genealogías queer, Black, trans, sex worker club histories y waacking/jazz roots.',
    atoms: ['bounce', 'wave', 'rockin', 'pause'],
    formulas: [],
    historicalContext: ['Big Freedia', 'New Orleans bounce', 'sex worker clubs', 'queer pride', 'trans women', 'Black women of color'],
    soundContext: ['bounce', 'hiphop', 'club bass'],
    invariants: JARRAS_INVARIANTS,
  },
  {
    id: 'safe-replay',
    title: 'Safe Replay / Consent First',
    purpose: 'Hace de la seguridad la estructura de toda práctica: pausa, consentimiento y salida.',
    atoms: ['pause'],
    formulas: [],
    historicalContext: ['community care', 'no coercion', 'no contact without agreement'],
    soundContext: ['silence as valid beat', 'breath clock'],
    invariants: JARRAS_INVARIANTS,
  },
])

const figureInvariant = JARRAS_INVARIANTS

export const FIGURE_SPECS: readonly JarrasFigureSpec[] = Object.freeze([
  {
    id: 'hyperlattice-course-map',
    batch: 'foundation',
    title: 'Twerk Hyperlattice',
    subtitle: 'cuerpo · ritmo · memoria · red · síntesis',
    moduleIds: ['pelvic-foundation', 'hiphop-groove', 'composition-lab', 'floor-metastability', 'somatic-sensorial', 'sound-synthesis', 'queer-bounce-lineage', 'safe-replay'],
    visualKernel: ['circular hyperlattice', 'black field', 'rainbow edges', 'gold Art Nouveau frame'],
    caption: 'Mapa completo del taller: técnica, groove, composición, somática, historia y síntesis sonora.',
    altText: 'Diagrama radial de conceptos del taller de twerk con anillos de técnica, groove, historia y sonido.',
    prompt: 'Art Nouveau inspired cyberpunk PACAZINE hyperlattice course map for a queer twerk workshop, black field, rainbow nodes, gold ornamental frame, didactic movement icons.',
    invariants: figureInvariant,
  },
  {
    id: 'pelvis-core',
    batch: 'foundation',
    title: 'Pelvis Core',
    subtitle: 'updown · jiggle · tiktok',
    moduleIds: ['pelvic-foundation', 'safe-replay'],
    visualKernel: ['pelvis oscillator', 'vertical arrow', 'micro-wave', 'lateral clock'],
    caption: 'La pelvis se escucha, se regula y se afina.',
    altText: 'Tres paneles explican updown vertical, jiggle vibratorio y tiktok lateral como movimientos pélvicos básicos.',
    prompt: 'Didactic figure titled Pelvis Core, showing updown, jiggle and tiktok as clean movement diagrams, non-invasive, dressed body diagram, Art Nouveau cyberpunk PACAZINE style.',
    invariants: figureInvariant,
  },
  {
    id: 'hiphop-groove',
    batch: 'foundation',
    title: 'Groove Hiphop',
    subtitle: 'bounce · wave · rockin',
    moduleIds: ['hiphop-groove', 'queer-bounce-lineage'],
    visualKernel: ['spring', 'sine wave', 'pendulum weight shift'],
    caption: 'Groove = peso + pulso + memoria.',
    altText: 'Figura pedagógica con tres rutas corporales: rebote vertical, onda continua y transferencia de peso.',
    prompt: 'Hiphop groove teaching plate, bounce wave rockin movement paths, neon black field, ornamental frame, queer club memory, clean arrows and nodes.',
    invariants: figureInvariant,
  },
  {
    id: 'cuadradinho-brega-funk',
    batch: 'foundation',
    title: 'Cuadradinho Brega Funk',
    subtitle: 'tiktok + updown',
    moduleIds: ['composition-lab'],
    visualKernel: ['square geometry', 'four corners', 'syncopated pulse'],
    caption: 'Cuadradinho abre cuatro esquinas para que el pulso suba y baje.',
    altText: 'Geometría cuadrada que combina tiktok lateral y updown vertical en cuatro puntos rítmicos.',
    prompt: 'Cuadradinho Brega Funk movement formula, square geometry, tiktok plus updown, cyberpunk Art Nouveau instructional card.',
    invariants: figureInvariant,
  },
  {
    id: 'hexagonin-jaraniano',
    batch: 'foundation',
    title: 'Hexagonín Jaraniano',
    subtitle: 'tiktok + updown + shake',
    moduleIds: ['composition-lab', 'sound-synthesis'],
    visualKernel: ['hexagon', 'sixfold cycle', 'shake accent'],
    caption: 'Seis direcciones, tres átomos, una traza replay-safe.',
    altText: 'Hexágono de movimiento que combina tiktok, updown y shake con pulso Click42.',
    prompt: 'Hexagonin Jaraniano dance formula, sixfold hexagon path, tiktok updown shake, Click42 pulse, PACAZINE black rainbow gold.',
    invariants: figureInvariant,
  },
  {
    id: 'jarras-choreo-transitions',
    batch: 'transition-somatic',
    title: 'Jarras Choreo',
    subtitle: 'transition engine',
    moduleIds: ['composition-lab', 'eulerian-improvisation'],
    visualKernel: ['graph of transitions', 'wave bounce rockin nodes', 'free route'],
    caption: 'Transición = cuidado entre dos intensidades.',
    altText: 'Grafo de transiciones entre wave, bounce, rockin, floor, jiggle, pause y shake.',
    prompt: 'Jarras Choreo transition engine graph, wave bounce rockin floor pause shake nodes, no mandatory route, safe replay, cyberpunk Art Nouveau.',
    invariants: figureInvariant,
  },
  {
    id: 'floor-drops-metastable',
    batch: 'transition-somatic',
    title: 'Floor Drops',
    subtitle: 'groove → estado metaestable',
    moduleIds: ['floor-metastability', 'safe-replay'],
    visualKernel: ['descending energy curve', 'floor support', 'return path'],
    caption: 'Caer no es fallar. Caer puede modular la energía.',
    altText: 'Secuencia de descenso regulado al suelo, pausa metaestable y retorno cuidadoso.',
    prompt: 'Floor drops to metastable state, safe floorwork sequence, support and recovery, dressed body diagram, PACAZINE style.',
    invariants: figureInvariant,
  },
  {
    id: 'somatic-sensorial',
    batch: 'transition-somatic',
    title: 'Somatic Sensorial',
    subtitle: 'siente · disfruta · percibe',
    moduleIds: ['somatic-sensorial', 'safe-replay'],
    visualKernel: ['inner senses', 'outer senses', 'skin boundary'],
    caption: 'La frontera no solo separa: también informa.',
    altText: 'Cuerpo rodeado por campos de sentidos internos y externos, con la piel como frontera informativa.',
    prompt: 'Somatic sensory dance plate, skin boundary, inner and outer senses, breath, floor, music, distance, Art Nouveau cyberpunk educational figure.',
    invariants: figureInvariant,
  },
  {
    id: 'eulerian-random-path',
    batch: 'transition-somatic',
    title: 'Impro Euleriana',
    subtitle: 'random path · hiphop phrases',
    moduleIds: ['eulerian-improvisation'],
    visualKernel: ['movement graph', 'visited nodes', 'return to center'],
    caption: 'Improvisar es encontrar una ruta que el cuerpo pueda recordar.',
    altText: 'Ruta luminosa que visita nodos de updown, tiktok, bounce, wave, rockin, floor, pause y shake.',
    prompt: 'Eulerian random path for hiphop movement improvisation, graph nodes and route returning to center, PACAZINE black neon gold.',
    invariants: figureInvariant,
  },
  {
    id: 'psychedelic-postclub',
    batch: 'history-sound-synthesis',
    title: 'Psicodelia Postclub',
    subtitle: 'anatólica · arábica · turca · francesa',
    moduleIds: ['somatic-sensorial', 'sound-synthesis'],
    visualKernel: ['sound layers', 'spirals', 'bass field', 'fragmented voice'],
    caption: 'La música no acompaña al cuerpo: lo reconfigura.',
    altText: 'Capas sonoras psicodélicas y postclub con espirales, bajo, repetición, trance y ruptura.',
    prompt: 'Psychedelic postclub sound field, Anatolian Arabic Turkish French postdisco posthouse posttechno layers, body response diagrams, cyberpunk Art Nouveau.',
    invariants: figureInvariant,
  },
  {
    id: 'quantum-instrumentality',
    batch: 'history-sound-synthesis',
    title: 'Quantum Instrumentality',
    subtitle: 'body as synth',
    moduleIds: ['sound-synthesis', 'composition-lab'],
    visualKernel: ['body as modular synth', 'Moog', 'Click42', 'Synclavier'],
    caption: 'El cuerpo no sigue el beat: también lo programa.',
    altText: 'Cuerpo mapeado como sintetizador modular: pelvis oscilador, respiración envelope, columna filtro, pies reloj.',
    prompt: 'Quantum Instrumentality body as synthesizer, Moog Moroder Daft Punk Click24 Click42 Synclavier Frank Zappa SonicPi, educational PACAZINE plate.',
    invariants: figureInvariant,
  },
  {
    id: 'queer-bounce-history',
    batch: 'history-sound-synthesis',
    title: 'Bounce · Kuir History',
    subtitle: 'archivo vivo de club, orgullo y resistencia',
    moduleIds: ['queer-bounce-lineage', 'safe-replay'],
    visualKernel: ['lineage map', 'club archive', 'respect gate'],
    caption: 'Bailar también es citar a quienes abrieron la pista.',
    altText: 'Mapa de genealogías de bounce, hiphop, waacking, jazz, sex worker clubs, queer pride, trans women and Black women of color.',
    prompt: 'Queer bounce history lineage map, Big Freedia, New Orleans bounce, hiphop, waacking, jazz, sex worker clubs, queer pride, trans women, Black women of color, respectful archive style.',
    invariants: figureInvariant,
  },
  {
    id: 'safe-replay-consent-first',
    batch: 'history-sound-synthesis',
    title: 'Safe Replay',
    subtitle: 'consent first',
    moduleIds: ['safe-replay'],
    visualKernel: ['pause icon', 'consent boundary', 'group care', 'exit route'],
    caption: 'La seguridad no aparece al final: es la estructura.',
    altText: 'Iconos de pausa, intensidad regulable, no contacto sin acuerdo, mirar participa, salir practica y cuidado del grupo.',
    prompt: 'Safe Replay Consent First educational card, pause intensity consent no contact without agreement, group care, black neon Art Nouveau PACAZINE.',
    invariants: figureInvariant,
  },
])

const basePreserves: readonly JarrasInvariant[] = Object.freeze([
  'no_transport',
  'safe_replay',
  'trace_preserved',
  'pi_fixed',
])

export const HYPERLATTICE_NODES: readonly HyperlatticeNode[] = Object.freeze([
  { id: 'GLOBAL_SECTION_PACAPDG', label: 'GLOBAL SECTION PACAPDG', layer: 'global', section: 'global', weight: 1 },
  { id: 'pelvic-foundation', label: 'Pelvis Core', layer: 'pelvis', section: 'local', weight: 0.9 },
  { id: 'hiphop-groove', label: 'Groove Hiphop', layer: 'groove', section: 'local', weight: 0.9 },
  { id: 'composition-lab', label: 'Composition Lab', layer: 'composition', section: 'local', weight: 0.85 },
  { id: 'floor-metastability', label: 'Floor / Metaestable', layer: 'floorwork', section: 'boundary', weight: 0.8 },
  { id: 'somatic-sensorial', label: 'Sensorial Somatic', layer: 'somatic', section: 'boundary', weight: 0.8 },
  { id: 'eulerian-improvisation', label: 'Impro Euleriana', layer: 'composition', section: 'local', weight: 0.75 },
  { id: 'sound-synthesis', label: 'Quantum Instrumentality', layer: 'sound', section: 'local', weight: 0.75 },
  { id: 'queer-bounce-lineage', label: 'Bounce Kuir History', layer: 'history', section: 'boundary', weight: 0.95 },
  { id: 'safe-replay', label: 'Safe Replay', layer: 'safety', section: 'boundary', weight: 1 },
])

export const HYPERLATTICE_EDGES: readonly HyperlatticeEdge[] = Object.freeze([
  { source: 'pelvic-foundation', target: 'composition-lab', relation: 'combines', via: 'JARRAS_CHOREO', preserves: basePreserves },
  { source: 'hiphop-groove', target: 'composition-lab', relation: 'combines', via: 'JARRAS_CHOREO', preserves: basePreserves },
  { source: 'composition-lab', target: 'eulerian-improvisation', relation: 'transitions', via: 'CLICK42', preserves: basePreserves },
  { source: 'eulerian-improvisation', target: 'GLOBAL_SECTION_PACAPDG', relation: 'glues', via: 'PACAPDG', preserves: basePreserves },
  { source: 'floor-metastability', target: 'safe-replay', relation: 'validates', via: 'KAPSYLA', preserves: basePreserves },
  { source: 'somatic-sensorial', target: 'safe-replay', relation: 'validates', via: 'KAPSYLA', preserves: basePreserves },
  { source: 'sound-synthesis', target: 'composition-lab', relation: 'sonifies', via: 'SIGILPI', preserves: basePreserves },
  { source: 'queer-bounce-lineage', target: 'hiphop-groove', relation: 'historicizes', via: 'PACAUAP', preserves: basePreserves },
  { source: 'safe-replay', target: 'GLOBAL_SECTION_PACAPDG', relation: 'glues', via: 'PACAPDG', preserves: basePreserves },
])

export const COURSE_HYPERLATTICE: CourseHyperlattice = Object.freeze({
  nodes: HYPERLATTICE_NODES,
  edges: HYPERLATTICE_EDGES,
  globalSection: 'GLOBAL_SECTION_PACAPDG',
})
