import {
  generatePalette as generateAccessiblePalette,
  toCSSTokens as toAccessibleCSSTokens,
  validatePairings as validateAccessiblePairings,
} from 'accessible-color-palette'
import type {
  PaletteResult,
  PluralSigilAgentExposition,
  PluralSigilFlow,
  PluralSigilInjection,
  PluralSigilInput,
  PluralSigilIssue,
  PluralSigilPairing,
  PluralSigilPrimitive,
  PluralSigilReport,
  PluralSigilRuntime,
  PluralSigilStage,
  PluralSigilValidation,
  Theme,
} from '../types.js'

const KQC_STAGES: PluralSigilStage[] = ['SIGIL', 'QUANTIZED', 'CANONICAL']
const STANDARDS = ['KQC', 'PACAPDG', 'PACAUAP', 'WCAG-2.2-AA'] as const
const RUNTIMES: PluralSigilRuntime[] = ['django', 'qquapp', 'w3c-wcag', 'agent']
const FORK = 'jbermejovega/universal-abstrakta-plural-aesthetik'

const KQC_FLOW: PluralSigilFlow[] = [
  {
    stage: 'SIGIL',
    ordinal: 1,
    invariant: 'Prototype every injected method in SIGIL form before release.',
    primitive: 'PACAPDG',
  },
  {
    stage: 'QUANTIZED',
    ordinal: 2,
    invariant: 'Quantize pairings through WCAG AA validation from accessible-color-palette.',
    primitive: 'PACAUAP',
  },
  {
    stage: 'CANONICAL',
    ordinal: 3,
    invariant: 'Release only after KQC order and all pairings pass.',
    primitive: 'PACAUAP',
  },
]

type AccessibleValidation = ReturnType<typeof validateAccessiblePairings>

function buildKqcFlow(): PluralSigilFlow[] {
  return KQC_FLOW.map((step) => ({ ...step }))
}

function normalizeBackground(background: string, theme: Theme): string {
  return background === 'theme' ? theme : background
}

function normalizePairing(pairing: PluralSigilPairing, theme: Theme): PluralSigilPairing {
  return {
    foreground: pairing.foreground,
    background: normalizeBackground(pairing.background, theme),
  }
}

function injectionPairings(injection: PluralSigilInjection, fallback: PluralSigilPairing[]): PluralSigilPairing[] {
  return injection.pairings ?? fallback
}

function stagesMatchKqc(stages: PluralSigilStage[]): boolean {
  return stages.length === KQC_STAGES.length && stages.every((stage, index) => stage === KQC_STAGES[index])
}

function buildKqcIssues(stages: PluralSigilStage[]): PluralSigilIssue[] {
  if (stagesMatchKqc(stages)) {
    return []
  }

  return [
    {
      code: 'KQC_ORDER',
      severity: 'error',
      path: 'stages',
      message: `KQC order must be ${KQC_STAGES.join(' -> ')}, received ${stages.join(' -> ')}`,
    },
  ]
}

function toPluralValidation(report: AccessibleValidation): PluralSigilValidation {
  return {
    summary: report.summary,
    allPass: report.allPass,
    pairings: report.pairings.map((pairing) => ({
      foreground: pairing.foreground,
      background: pairing.background,
      level: pairing.level,
      message: pairing.message,
      ...(pairing.hex === undefined ? {} : { hex: pairing.hex }),
    })),
  }
}

function buildPairingIssues(validation: PluralSigilValidation): PluralSigilIssue[] {
  return validation.pairings
    .filter((pairing) => pairing.level === 'fail' || pairing.level === 'invalid')
    .map((pairing) => ({
      code: 'WCAG_PAIRING',
      severity: 'error',
      path: `pairings.${pairing.foreground}.${pairing.background}`,
      message: pairing.message,
    }))
}

function commentBlock(language: string, lines: string[]): string {
  const normalized = language.toLowerCase()

  if (normalized === 'python') {
    return lines.map((line) => `# ${line}`).join('\n')
  }

  if (normalized === 'django-template') {
    return lines.map((line) => `{# ${line} #}`).join('\n')
  }

  if (normalized === 'html') {
    return ['<!--', ...lines.map((line) => `  ${line}`), '-->'].join('\n')
  }

  return ['/*', ...lines.map((line) => ` * ${line}`), ' */'].join('\n')
}

function injectSigilHeader(input: PluralSigilInput, injection: PluralSigilInjection): string {
  const header = commentBlock(injection.language, [
    `UAP SIGIL ${input.namespace}/${injection.id}`,
    `KQC: ${KQC_STAGES.join(' -> ')}`,
    `Palette: accessible-color-palette ${input.sourceHex} on ${input.theme}`,
    `Standards: ${STANDARDS.join(', ')}`,
  ])

  return `${header}\n${injection.code}`
}

function buildPalettePrimitive(
  input: PluralSigilInput,
  palette: PaletteResult,
  cssTokens: string,
  pairings: PluralSigilPairing[],
): PluralSigilPrimitive {
  return {
    kind: 'PACAUAP',
    id: `${input.namespace}:palette`,
    namespace: input.namespace,
    method: 'canonical-invariant-flow',
    payload: { palette, cssTokens },
    bindings: pairings,
    flow: buildKqcFlow(),
    standards: [...STANDARDS],
    exposition:
      'PACAUAP palette primitive generated by accessible-color-palette and gated by WCAG 2.2 AA pairings.',
  }
}

function buildInjectionPrimitive(
  input: PluralSigilInput,
  injection: PluralSigilInjection,
  fallbackPairings: PluralSigilPairing[],
): PluralSigilPrimitive {
  return {
    kind: 'PACAPDG',
    id: `${input.namespace}:${injection.id}`,
    namespace: input.namespace,
    method: injection.method ?? 'plural-method',
    payload: {
      code: injectSigilHeader(input, injection),
      language: injection.language,
    },
    bindings: injectionPairings(injection, fallbackPairings).map((pairing) => normalizePairing(pairing, input.theme)),
    flow: buildKqcFlow(),
    standards: [...STANDARDS],
    exposition:
      'PACAPDG code primitive exposed for Django workflows, QQUAPP injection, W3C WCAG review, and agent planning.',
  }
}

function buildAgentExposition(namespace: string): PluralSigilAgentExposition {
  return {
    name: namespace,
    purpose: 'single-purpose KQC linter and PACA primitive transpiler',
    externalDependency: 'accessible-color-palette',
    runtimes: [...RUNTIMES],
    standards: [...STANDARDS],
  }
}

export function lintPluralSigil(input: PluralSigilInput): PluralSigilReport {
  const stages = [...(input.stages ?? KQC_STAGES)]
  const palette = generateAccessiblePalette(input.sourceHex, input.theme)
  const pairings = input.pairings.map((pairing) => normalizePairing(pairing, input.theme))
  const injectedPairings = input.injections.flatMap((injection) =>
    injectionPairings(injection, input.pairings).map((pairing) => normalizePairing(pairing, input.theme)),
  )
  const validation = toPluralValidation(validateAccessiblePairings(palette, [...pairings, ...injectedPairings]))
  const cssTokens = toAccessibleCSSTokens(palette, input.cssPrefix ?? 'uap')
  const issues = [...buildKqcIssues(stages), ...buildPairingIssues(validation)]
  const ok = issues.every((issue) => issue.severity !== 'error') && validation.allPass
  const primitives = [
    buildPalettePrimitive(input, palette, cssTokens, pairings),
    ...input.injections.map((injection) => buildInjectionPrimitive(input, injection, pairings)),
  ]

  return {
    ok,
    rule: 'KQC',
    source: 'accessible-color-palette',
    stages,
    flow: buildKqcFlow(),
    palette,
    validation,
    primitives,
    issues,
    agentExposition: buildAgentExposition(input.namespace),
    release: {
      fork: FORK,
      canonical: ok,
    },
  }
}
